spring.application.name=student-service
my.app=hello
spring.config.import:configserver:http://localhost:8888

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.flyway.locations=classpath:db/migration